name: GitHub Telegram Notifier
on: [push]
jobs:          
  send_message:
    runs-on: ubuntu-latest
	  message: &message |
            ${{ github.actor }} опубликовал коммит:
            Сообщение коммита: ${{ github.event.commits[0].message }}
            
            Репозиторий: ${{ github.repository }}
            
            Изменения в коммите: https://github.com/${{ github.repository }}/commit/${{github.sha}}
    steps:
    - name: Send Telegram Message
      run: |
        curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=${message}&message_thread_id=${{ secrets.TELEGRAM_MSG_THREAD_ID }}"

