name: GitHub Telegram Notifier
on: [push]
env:
  message: |
          **${{ github.actor }}** опубликовал коммит:
          **Ветка:** ${{ github.ref_name }}
          **Сообщение коммита**: ${{ github.event.commits[0].message }}
          **Репозиторий**: ${{ github.repository }}
          **Изменения в коммите**: https://github.com/${{ github.repository }}/commit/${{github.sha}}
jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Message
      run: |
        curl -s -X POST 'https://api.telegram.org/bot${{ secret.TELEGRAM_TOKEN }}/sendMessage' \
        -d "chat_id=${{ secret.TELEGRAM_CHAT_ID }}&text=${{ env.message }}&message_thread_id=${{ secret.TELEGRAM_MSG_THREAD_ID }}"

