name: GitHub Telegram Notifier
on: [push]

jobs:
  send_commit_message:
    runs-on: ubuntu-latest
    env:
      message: |
        *${{ github.actor }}* опубликовал коммит:
        *Ветка:* ${{ github.ref_name }}
        *Сообщение коммита*: ${{ github.event.head_commit.message }}
        *Репозиторий*: ${{ github.repository }}
        *Изменения в коммите*: https://github.com/${{ github.repository }}/commit/${{github.sha}}
    steps:
    - name: Send Telegram Message
      run: |
        curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=${{ env.message }}&message_thread_id=${{ secrets.TELEGRAM_MSG_THREAD_ID }}&parse_mode=Markdown"